function [fitresult, gof] = fit_gauss_power_function(X, Y, Z, W)
%CREATEFIT(X,Y,Z,W)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: Z
%      Weights : W
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jun-2014 03:52:47


%% Fit: 'untitled fit 1'.
[xData, yData, zData, weights] = prepareSurfaceData( X, Y, Z, W );

% Set up fittype and options.
ft = fittype( 'a*exp(-x^2/b)*y^(c)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -3];
opts.Robust = 'LAR';
opts.StartPoint = [0.0344 0.438744359656398 -2];
opts.Upper = [Inf Inf -1];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'Z vs. X, Y with W', 'Location', 'NorthEast' );
% Label axes
xlabel( 'X' );
ylabel( 'Y' );
zlabel( 'Z' );
grid on
view( -37.5, 52.0 );


